### ISSUE TITLE
PS: improve metrics

### ISSUE THREAD

**Issue by kormat** [scionproto/scion#3106]
- [x] Segment registrations by AS and type (a given AS will only register a single type of segment, but this allows querying along either axis). (done by #3152)
- [x] Segment registrations by update (i.e. it already exists in pathdb) vs new. (done by #3152)
- [x] Segment requests by type (up/down/core) and number of segments and revocations returned. Have label to indicate status of CacheOnly flag. (done by #3232)
- [x] Segment requests errors by type (up/down/core) and error type. (details https://github.com/scionproto/scion/issues/3106#issuecomment-528821888) (done by #3232)
- [x] segsyncer metrics. (done by #3241)
- [x] Revocations received. (details https://github.com/scionproto/scion/issues/3106#issuecomment-531679988)
- [x] ~SCMP errors received.~ Replaced by #3107, for now. Eventually it would be nice to know what actions got an scmp error reply.
- [x] Crypto issues:
  - [x] cert/trc request failures: timeouts vs not available
  - [x] Signature verification failed (e.g. possible forgery)
  - [x] Signature validation failed (e.g. signature from expired cert)
- [x] ~Dispatcher errors/reconnects.~ Replaced by #3107 
- [x] Implement https://github.com/scionproto/scion/issues/3121 for all periodic tasks

**Comment by lukedirtwalker** [comment]
Currently we have request counts handled generally in the messenger. We could expand the Handler interface to provide more information about a request and additional metric labels, so that we can still keep this in the messenger.

**Comment by kormat** [comment]
@lukedirtwalker : that will works for some stuff, but not others. E.g. knowing whether a registration is updating an existing segment or not requires the business logic of the PS.

**Comment by lukedirtwalker** [comment]
@kormat that can only be decided ~after the handler is done, so it could be in a map in the handler result (maybe?)

**Comment by kormat** [comment]
It gets hard to handle this in a generic way. E.g. a path registration should indicate the type (up/down/core) in the "result", plus whether it's an update or new. A path request should indicate the type (up/down/core) and cache_only status in the "result". It seems likely to end up a real mess.

**Comment by kormat** [comment]
As an example of what i'm thinking of:
```
# Number of path registrations. "result" can be one of: new, updated, err_crypto, err_db
pathsrv_registrations_total{elem="ps1-1-1", type="up", src_ia="1-34", result="updated"} 443
# Number of path requests. Incremented by one for every request. "result" can be one of: cached, fetched, err_crypto, err_db, err_timeout.
pathsrv_requests_total{elem="ps1-1-1", type="core", cache_only="false", dst_isd="3", result="fetched"} 11
# Number of segments in replies to path requests. Could be a histogram later if we really wanted more insight. Incremented by the number of segments in a reply.
pathsrv_requests_reply_segs_total(elem="ps1-1-1", type="core", cache_only="false", dst_isd="3"} 32
```

**Comment by lukedirtwalker** [comment]
@kormat question:
`Revocations received.` should that also include revocations received as part of a `SegReply` ?

**Comment by kormat** [comment]
Yeah, i think we want a metric for revocations received, with a label to say whether it's:
- part of a SegReply
- a top-level PathMgmt.sRevInfo
- an SCMP revocation

and another label to say what the result is (expired, crypto not available, invalid, ok, etc).

**Comment by lukedirtwalker** [comment]
segsyncer metrics:
```
# Number of segments received from segment syncing "result" can be one of: new, updated, err_crypto, err_db
ps_sync_regs_total{elem="ps1-1-1", type="up", src_ia="1-34", result="updated"} 93
# Number of segment syncer executions
ps_segsyncer_pushes_total{elem="ps1-1-1", dst_ia="1-32", result="ok_succsess"} 31
```

**Comment by lukedirtwalker** [comment]
All metrics should be in by now. If there is something missing we should create a new issue.
